name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Bistard
          template: classic
          config_display: large
          base: header
          config_timezone: America/New_York
          config_order: base.header, lines, repositories, habits, languages, leetcode, activity
        
          base_indepth: yes
          repositories_affiliations: owner
          commits_authoring: Bistard@github.com, 1015813038@qq.com, lshh1015813038@gmail.com
        
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_user: Bistardd
    
          plugin_languages: yes
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: Java
          plugin_repositories_skipped: "2021-DWZQ-coop\noj"
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Bistard/nota@master
          plugin_languages_details: lines, percentage
          plugin_languages_analysis_timeout: 60
          
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_featured: Bistard/nota
          
          
          
          
          plugin_activity: no
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_filter: all
          
          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_achievements_secrets: no
          plugin_achievements_threshold: B
          plugin_habits: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_charts: no
          plugin_habits_from: 1000
          
